apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fe-deployment
spec:
  template:
    metadata:
      name: nginx-fe
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx-fe
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      tier: frontend
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fe-svc
  labels:
    tier: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    tier: frontend
