apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
    - name: nginx-on-ssd
      image: nginx
      imagePullPolicy: IfNotPresent
  nodeSelector:
    disk: ssd
